name: Rustdoc

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build rustdoc
        run: cargo doc --no-deps
